arguments:
  gitlab-url: "https://gitlab.example.org"
  gitlab-token: "GITLAB_TOKEN"
options:
  ignore: "(^namespace_name|^namespace\/project)"
  homepage: "https://satis.example.org"
  output: "satis.json"
  template: 'satis-template.example.json'
  use-file-to-include: '.satisinclude'
basic-auth:
  auth-name: "Satis Repository"
  auth-file: "/path/to/.htpasswd" # Absolute path required
  username: "admin"
  password: "password"