arguments:
  url: "https://gitlab.example.org"
  token: "GITLAB_TOKEN"
options:
  ignore: "(^namespace_name|^namespace\/project)"
  homepage: "https://satis.example.org"
  output: "satis.json"
basic-auth:
  auth-name: "Satis Repository"
  auth-file: "/path/to/.htpasswd" # Absolute path required
  username: "admin"
  password: "password"